switch("debugger", "native")
switch("lineDir", "on")
switch("define", "debug")
switch("verbosity", "0")
switch("hints", "off")
switch("warnings", "off")
# switches for compiling with coverage
switch("passC", "-fprofile-arcs")
switch("passC", "-ftest-coverage")
switch("passL", "-fprofile-arcs")
switch("passL", "-ftest-coverage")
