services:
  storage-node1:
    image: logosstorage/logos-storage-nim:latest
    environment:
      - STORAGE_LOG_LEVEL=${STORAGE_LOG_LEVEL:-TRACE}
      - STORAGE_METRICS=${STORAGE_METRICS:-false}
      - STORAGE_METRICS_ADDRESS=${STORAGE_METRICS_ADDRESS:-0.0.0.0}
      - STORAGE_METRICS_PORT=${STORAGE_METRICS_PORT:-8008}
      - STORAGE_DATA_DIR=${STORAGE_DATA_DIR:-/datadir}
      - STORAGE_LISTEN_ADDRS=${STORAGE_LISTEN_ADDRS:-/ip4/0.0.0.0/tcp/2345}
      - STORAGE_NAT=${STORAGE_NAT:-10.0.0.10}
      - STORAGE_DISC_PORT=${STORAGE_DISC_PORT:-8090}
      - STORAGE_NET_PRIVKEY=${STORAGE_NET_PRIVKEY:-key}
      # - STORAGE_BOOTSTRAP_NODE=${STORAGE_BOOTSTRAP_NODE}
      - STORAGE_MAX_PEERS=${STORAGE_MAX_PEERS:-160}
      - STORAGE_AGENT_STRING=${STORAGE_AGENT_STRING:-LogosStorage}
      - STORAGE_API_BINDADDR=${STORAGE_API_BINDADDR:-0.0.0.0}
      - STORAGE_API_PORT=${STORAGE_API_PORT:-8080}
      - STORAGE_REPO_KIND=${STORAGE_REPO_KIND:-fs}
      - STORAGE_STORAGE_QUOTA=${STORAGE_STORAGE_QUOTA:-8589934592}
      - STORAGE_BLOCK_TTL=${STORAGE_BLOCK_TTL:-0}
      # - STORAGE_BLOCK_MI=${STORAGE_BLOCK_MI}
      - STORAGE_BLOCK_MN=${STORAGE_BLOCK_MN:-1000}
      - STORAGE_CACHE_SIZE=${STORAGE_CACHE_SIZE:-0}
      - NAT_IP_AUTO=false
      - NAT_PUBLIC_IP_AUTO=https://ipinfo.io/ip
    ports:
      - 8080:8080/tcp # REST API
      - 8008:8008/tcp # Metrics
      - 2345:2345/tcp # libp2p
      - 8090:8090/udp # DHT discovery
    volumes:
      - ./datadir:/datadir:z
    networks:
      - logosstorage
networks:
  logosstorage:
    driver: bridge
