apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: ${CA}
    server: ${SERVER}
  name: release-tests
contexts:
- context:
    cluster: release-tests
    user: release-tests-runner
  name: release-tests
current-context: release-tests
users:
- name: release-tests-runner
  user:
    token: ${TOKEN}
