#!/usr/bin/env bash
echo "["
echo "{\"os\": \"linux\",   \"cpu\": \"amd64\", \"builder\": \"ubuntu-latest\",  \"tests\": \"unittest\",    \"nim_version\": \"${nim_version}\", \"shell\": \"bash --noprofile --norc -e -o pipefail\"},"
echo "{\"os\": \"linux\",   \"cpu\": \"amd64\", \"builder\": \"ubuntu-latest\",  \"tests\": \"contract\",    \"nim_version\": \"${nim_version}\", \"shell\": \"bash --noprofile --norc -e -o pipefail\"},"
echo "{\"os\": \"linux\",   \"cpu\": \"amd64\", \"builder\": \"ubuntu-latest\",  \"tests\": \"integration\", \"nim_version\": \"${nim_version}\", \"shell\": \"bash --noprofile --norc -e -o pipefail\"},"
echo "{\"os\": \"linux\",   \"cpu\": \"amd64\", \"builder\": \"ubuntu-latest\",  \"tests\": \"tools\",       \"nim_version\": \"${nim_version}\", \"shell\": \"bash --noprofile --norc -e -o pipefail\"},"
echo "{\"os\": \"macos\",   \"cpu\": \"arm64\", \"builder\": \"macos-14\",       \"tests\": \"unittest\",    \"nim_version\": \"${nim_version}\", \"shell\": \"bash --noprofile --norc -e -o pipefail\"},"
echo "{\"os\": \"macos\",   \"cpu\": \"arm64\", \"builder\": \"macos-14\",       \"tests\": \"contract\",    \"nim_version\": \"${nim_version}\", \"shell\": \"bash --noprofile --norc -e -o pipefail\"},"
echo "{\"os\": \"macos\",   \"cpu\": \"arm64\", \"builder\": \"macos-14\",       \"tests\": \"integration\", \"nim_version\": \"${nim_version}\", \"shell\": \"bash --noprofile --norc -e -o pipefail\"},"
echo "{\"os\": \"macos\",   \"cpu\": \"arm64\", \"builder\": \"macos-14\",       \"tests\": \"tools\",       \"nim_version\": \"${nim_version}\", \"shell\": \"bash --noprofile --norc -e -o pipefail\"},"
echo "{\"os\": \"windows\", \"cpu\": \"amd64\", \"builder\": \"windows-latest\", \"tests\": \"unittest\",    \"nim_version\": \"${nim_version}\", \"shell\": \"msys2\"},"
echo "{\"os\": \"windows\", \"cpu\": \"amd64\", \"builder\": \"windows-latest\", \"tests\": \"contract\",    \"nim_version\": \"${nim_version}\", \"shell\": \"msys2\"},"
echo "{\"os\": \"windows\", \"cpu\": \"amd64\", \"builder\": \"windows-latest\", \"tests\": \"integration\", \"nim_version\": \"${nim_version}\", \"shell\": \"msys2\"},"
echo "{\"os\": \"windows\", \"cpu\": \"amd64\", \"builder\": \"windows-latest\", \"tests\": \"tools\",       \"nim_version\": \"${nim_version}\", \"shell\": \"msys2\"}"
echo "]"
