name: Conventional Commits Linting

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
  merge_group:

pr-title:
  runs-on: ubuntu-latest
  if: github.event_name == 'pull_request'
  steps:
    - name: PR Conventional Commit Validation
      uses:  ytanikin/pr-conventional-commits@1.4.1
      with:
        task_types: '["feat","fix","docs","test","ci","build","refactor","style","perf","chore","revert"]'
