{
 "title": "Codex Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(process_virtual_memory_bytes,node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Codex Inflight Discovery",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "codex_inflight_discovery{}" }
   ]
  },
  {
   "title": "GC heap objects #${node}",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nim_gc_heap_instance_occupied_bytes{node=\"${node}\"}",
     "legendFormat": "{{type_name}}"
    }
   ]
  },
  {
   "title": "RSS mem #${node}",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{node=\"${node}\"}"
    }
   ]
  },
  {
   "title": "CPU usage #${node}",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{job=\"codex\"}[1m])"
    }
   ]
  },
  {
   "title": "resources #${node}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{node=\"${node}\"}[2s]) * 100",
     "legendFormat": "CPU usage %"
    },
    {
     "expr": "process_open_fds{node=\"${node}\"}",
     "legendFormat": "open file descriptors"
    },
    {
     "expr": "process_resident_memory_bytes{node=\"${node}\"}",
     "legendFormat": "RSS"
    },
    {
     "expr": "nim_gc_mem_bytes{node=\"${node}\"}",
     "legendFormat": "Nim GC mem total"
    },
    {
     "expr": "nim_gc_mem_occupied_bytes{node=\"${node}\"}",
     "legendFormat": "Nim GC mem used"
    }
   ]
  },
  { "title": "libp2p", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "libp2p peers #${node}",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(type) (libp2p_peers{node=\"${node}\"})",
     "legendFormat": "connected peers"
    },
    {
     "expr": "sum (libp2p_pubsub_peers{node=\"${node}\"})",
     "legendFormat": "pubsub peers"
    },
    {
     "expr": "sum (nbc_peers{node=\"${node}\"})",
     "legendFormat": "nbc peers"
    }
   ]
  },
  {
   "title": "libp2p open streams #${node}",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(type) (libp2p_open_streams{node=\"${node}\"})",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum (libp2p_open_streams{node=\"${node}\"})",
     "legendFormat": "combined"
    },
    {
     "expr": "sum by(type, dir) (libp2p_open_streams{node=\"${node}\"})",
     "legendFormat": "{{type}, {dir}}"
    }
   ]
  },
  {
   "title": "libp2p mplex channels #${node}",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(initiator,node)(libp2p_mplex_channels{node=\"${node}\"})",
     "legendFormat": "initiator {{initiator}}"
    },
    {
     "expr": "sum(libp2p_mplex_channels{node=\"${node}\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "libp2p mplex channels per peer #${node}",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by(peer, initiator)(libp2p_mplex_channels{node=\"${node}\"}))",
     "legendFormat": "peer {{peer}}"
    }
   ]
  },
  { "title": "Discovery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Discovery Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "discovery_message_requests_incoming_total{}"
    },
    {
     "expr": "discovery_message_requests_outgoing_total{}"
    }
   ]
  },
  {
   "title": "Discovery LRU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "discovery_session_lru_cache_hits_total{}"
    },
    {
     "expr": "discovery_session_lru_cache_misses_total{}"
    }
   ]
  }
 ]
}